In [1]:
import numpy as np

def WriteVectorsFile(filename, N, *args):
    #Abre o arquivo e no modo de escrita, ai é possivel salvar
    f = open(filename, 'w')

    for i in range(0, N):
        for j in range(0, len(args)):
            # %s é uma referencia a C, o printf de C utiliza o %s para strings

            f.write('%s ' %(args[j][i]))

        f.write('\n')

    # Fecha o arquivo
    f.close()

def ReadVectorsFile(filename):

    # loadtxt retornar os vetores em uma matriz de N x M, onde n é o tamanho dos vetores e M é o número de vetores
    aux = np.loadtxt(filename)

    return aux

In [2]:
filename = 'test.txt'

v1 = [5, 4, 3]
v2 = [2, 4, 6]
v3 = [3, 6, 9]
v4 = [1, 5, 7]

WriteVectorsFile(filename, len(v1), v1, v2, v3, v4)

In [6]:

m = ReadVectorsFile(filename)

print(m)

# m[:, 0] acessa a primeira coluna da matriz que é o primeiro vetor
print(m[:, 0])

#ou pode transpor a matriz m e acessar dessa forma
mt = np.transpose(m)
print(mt[0])

[[5. 2. 3. 1.]
 [4. 4. 6. 5.]
 [3. 6. 9. 7.]]
[5. 4. 3.]
[5. 4. 3.]
